alter table SANGYO_STATION_AND_USER add constraint FK_SANGYO_STATION_AND_USER_ON_USER foreign key (USER_ID) references SEC_USER(ID);
create index IDX_SANGYO_STATION_AND_USER_ON_USER on SANGYO_STATION_AND_USER (USER_ID);
