alter table SANGYO_SCRAP_RECORD add constraint FK_SANGYO_SCRAP_RECORD_ON_SCREEN foreign key (SCREEN_ID) references SANGYO_SCREEN(ID);
create index IDX_SANGYO_SCRAP_RECORD_ON_SCREEN on SANGYO_SCRAP_RECORD (SCREEN_ID);
