alter table SANGYO_FINISHED add constraint FK_SANGYO_FINISHED_ON_SCREEN_ID foreign key (SCREEN_ID_ID) references SANGYO_SCREEN(ID);
create index IDX_SANGYO_FINISHED_ON_SCREEN_ID on SANGYO_FINISHED (SCREEN_ID_ID);
