alter table SANGYO_PRODUCTION_RECORDS add constraint FK_SANGYO_PRODUCTION_RECORDS_ON_SCREEN foreign key (SCREEN_ID) references SANGYO_SCREEN(ID);
create index IDX_SANGYO_PRODUCTION_RECORDS_ON_SCREEN on SANGYO_PRODUCTION_RECORDS (SCREEN_ID);
