alter table SANGYO_FINISHED add constraint FK_SANGYO_FINISHED_ON_WAREHOUSE_ID foreign key (WAREHOUSE_ID_ID) references SANGYO_WAREHOUSE(ID);
create index IDX_SANGYO_FINISHED_ON_WAREHOUSE_ID on SANGYO_FINISHED (WAREHOUSE_ID_ID);
