alter table SANGYO_DISPATCH_LIST add constraint FK_SANGYO_DISPATCH_LIST_ON_PROCEDURE foreign key (PROCEDURE_ID) references SANGYO_PROCEDURE(ID);
create index IDX_SANGYO_DISPATCH_LIST_ON_PROCEDURE on SANGYO_DISPATCH_LIST (PROCEDURE_ID);
