alter table SANGYO_UNQUALIFIED add constraint FK_SANGYO_UNQUALIFIED_ON_PROCEDURE foreign key (PROCEDURE_ID) references SANGYO_PROCEDURE(ID);
create index IDX_SANGYO_UNQUALIFIED_ON_PROCEDURE on SANGYO_UNQUALIFIED (PROCEDURE_ID);
