alter table SANGYO_PROCEDURE add constraint FK_SANGYO_PROCEDURE_ON_PROCESS_FLOW foreign key (PROCESS_FLOW_ID) references SANGYO_PROCESS_FLOW(ID);
create index IDX_SANGYO_PROCEDURE_ON_PROCESS_FLOW on SANGYO_PROCEDURE (PROCESS_FLOW_ID);
