alter table SANGYO_STOCK_ORDER add constraint FK_SANGYO_STOCK_ORDER_ON_ORDER foreign key (ORDER_ID) references SANGYO_ORDER(ID);
create index IDX_SANGYO_STOCK_ORDER_ON_ORDER on SANGYO_STOCK_ORDER (ORDER_ID);
