alter table SANGYO_SEMI add constraint FK_SANGYO_SEMI_ON_WAREHOUSE_ID foreign key (WAREHOUSE_ID_ID) references SANGYO_WAREHOUSE(ID);
create index IDX_SANGYO_SEMI_ON_WAREHOUSE_ID on SANGYO_SEMI (WAREHOUSE_ID_ID);
