alter table SANGYO_INVENTORY_CHECK add constraint FK_SANGYO_INVENTORY_CHECK_ON_ANNAL_USER foreign key (ANNAL_USER_ID) references SEC_USER(ID);
create index IDX_SANGYO_INVENTORY_CHECK_ON_ANNAL_USER on SANGYO_INVENTORY_CHECK (ANNAL_USER_ID);
