alter table SANGYO_UNQUALIFIED add constraint FK_SANGYO_UNQUALIFIED_ON_PROCESSOR foreign key (PROCESSOR_ID) references SEC_USER(ID);
create index IDX_SANGYO_UNQUALIFIED_ON_PROCESSOR on SANGYO_UNQUALIFIED (PROCESSOR_ID);
