alter table SANGYO_UNQUALIFIED add constraint FK_SANGYO_UNQUALIFIED_ON_WAREHOUSE_ID foreign key (WAREHOUSE_ID_ID) references SANGYO_WAREHOUSE(ID);
create index IDX_SANGYO_UNQUALIFIED_ON_WAREHOUSE_ID on SANGYO_UNQUALIFIED (WAREHOUSE_ID_ID);
