alter table SANGYO_FINISHED add constraint FK_SANGYO_FINISHED_ON_OPERATING_PERSONNEL foreign key (OPERATING_PERSONNEL_ID) references SEC_USER(ID);
create index IDX_SANGYO_FINISHED_ON_OPERATING_PERSONNEL on SANGYO_FINISHED (OPERATING_PERSONNEL_ID);
