alter table SANGYO_STATION_AND_USER add constraint FK_SANGYO_STATION_AND_USER_ON_STATION foreign key (STATION_ID) references SANGYO_STATION(ID);
create index IDX_SANGYO_STATION_AND_USER_ON_STATION on SANGYO_STATION_AND_USER (STATION_ID);
