alter table SANGYO_UNQUALIFIED add constraint FK_SANGYO_UNQUALIFIED_ON_SCREEN_ID foreign key (SCREEN_ID_ID) references SANGYO_SCREEN(ID);
create index IDX_SANGYO_UNQUALIFIED_ON_SCREEN_ID on SANGYO_UNQUALIFIED (SCREEN_ID_ID);
