alter table SANGYO_WORK_ORDER add constraint FK_SANGYO_WORK_ORDER_ON_ORDER_ID foreign key (ORDER_ID_ID) references SANGYO_ORDER(ID);
create index IDX_SANGYO_WORK_ORDER_ON_ORDER_ID on SANGYO_WORK_ORDER (ORDER_ID_ID);
