alter table SANGYO_PROCEDURE add constraint FK_SANGYO_PROCEDURE_ON_WORK_ORDER foreign key (WORK_ORDER_ID) references SANGYO_WORK_ORDER(ID);
create index IDX_SANGYO_PROCEDURE_ON_WORK_ORDER on SANGYO_PROCEDURE (WORK_ORDER_ID);
