alter table SANGYO_SEMI add constraint FK_SANGYO_SEMI_ON_OPERATING_PERSONNEL foreign key (OPERATING_PERSONNEL_ID) references SEC_USER(ID);
create index IDX_SANGYO_SEMI_ON_OPERATING_PERSONNEL on SANGYO_SEMI (OPERATING_PERSONNEL_ID);
