alter table SANGYO_SCREEN add constraint FK_SANGYO_SCREEN_ON_WORK_ORDER foreign key (WORK_ORDER_ID) references SANGYO_WORK_ORDER(ID);
create index IDX_SANGYO_SCREEN_ON_WORK_ORDER on SANGYO_SCREEN (WORK_ORDER_ID);
