alter table SANGYO_UNQUALIFIED add constraint FK_SANGYO_UNQUALIFIED_ON_WORK_ORDER foreign key (WORK_ORDER_ID) references SANGYO_WORK_ORDER(ID);
create index IDX_SANGYO_UNQUALIFIED_ON_WORK_ORDER on SANGYO_UNQUALIFIED (WORK_ORDER_ID);
