alter table SANGYO_PROCESS_FLOW_ID add constraint FK_SANGYO_PROCESS_FLOW_ID_ON_PROCEDURE foreign key (PROCEDURE_ID) references SANGYO_PROCEDURE(ID);
create index IDX_SANGYO_PROCESS_FLOW_ID_ON_PROCEDURE on SANGYO_PROCESS_FLOW_ID (PROCEDURE_ID);
